repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: trufflehog (pkgx)
        language: system          # pre-commit won’t try to pip-install
        entry: pkgx               # ↳ pkgx handles binaries & caching
        args:
          - trufflehog@3.89.1     # pin CLI release
          - git
          - file://.
          - --since-commit        # scan only what you’re adding
          - HEAD
          - --only-verified       # cut false-positives
          - --fail                # non-zero exit on leak
          - --exclude-paths
          - trufflehog-exclude-paths.txt
        pass_filenames: false     # let the args decide scope
        stages: [pre-commit, pre-push]  # new names  [oai_citation:2‡github.com](https://github.com/PyCQA/isort/issues/2294?utm_source=chatgpt.com)
