repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: trufflehog
        language: system
        entry: trufflehog
        args:
          - git
          - file://.
          - --since-commit
          - HEAD
          - --only-verified
          - --fail
          - --exclude-paths
          - trufflehog-exclude-paths.txt
        pass_filenames: false
        stages: [pre-push]

  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        language: system
        entry: gitleaks
        args:
          - protect
          - --staged
        pass_filenames: false
        stages: [pre-commit,pre-push]
