#!/bin/bash

[ ! "$_INIT_COMPLETE" ] && source $HOME/github/shell-settings/scripts/.INIT && export _INIT_COMPLETE=1

if ! command -v tldr &> /dev/null; then
  if command -v brew &> /dev/null; then
    brew install tlrc
  else
    i tldr
  fi
fi

tldr "$@"
