#!/bin/bash

[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT

if ! command -v tldr &> /dev/null; then
  if command -v brew &> /dev/null; then
    brew install tlrc
  else
    i tldr
  fi
fi

tldr "$@"
