#!/bin/bash

[ -z $SHELL_SETTINGS_DIR ] && source $HOME/github/shell-settings/scripts/.INIT

if ! command -v tldr &> /dev/null; then
  if command -v brew &> /dev/null; then
    brew install tlrc
  else
    i tldr
  fi
fi

tldr "$@"
