#!/bin/bash

[ ! "$_INIT_COMPLETE" ] && source $HOME/github/shell-settings/scripts/.INIT && export _INIT_COMPLETE=1

if ! command -v gron &> /dev/null; then
  log "command 'json' not found, installing gron now..."
  i gron
fi

gron "$@"
