#!/bin/bash

trap exit EXIT

exit() {
  pkill -i caffeinate
}

TIME_TO_KILL=${1:-720}

if command -v caffeinate &> /dev/null
then
  if [ $TIME_TO_KILL -gt 0 ]; then
    clear
    echo "killing automatically after $TIME_TO_KILL minutes"
    caffeinate -disu &
    caff_pid=$!
    sleep $(($TIME_TO_KILL * 60 )) && kill -9 $caff_pid
  else
    clear
    echo "Staying alive, staying alive..."
    caffeinate -disu
  fi
else
  echo "caffeinate not supported"
fi

