#!/bin/bash

[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT

__main() {
  set +u
  local commit="$1"
  set -u

  if [ "$commit" = "" ]; then
    die "commit sha required"
  fi

  log "Copying commit and message or something for \"${commit}\""
}

__main "$@"
