#!/bin/bash

[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/.INIT

main() {
  set +u
  local git_dir="${1}"
  set -u

  if [ ! -d "${git_dir}/.git" ]; then
    log "\"${git_dir}\" is not a git directory"
    return 1
  fi

  log "$@"
}

main "$@"
