#!/bin/bash

[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT

_PATH="$PATH"

run_installer() {
  echo "Just kidding"
}

__exists() {
  _PATH=""

  if [ $# -ne 1 ]; then
    echo "You can only check a single command at a time"
    return 1
  fi

  PATH="$(echo "$PATH" | tr ':' '\n' | grep -v 'shell-settings' | tr '\n' ':' | uniq | sed 's/.$//')"

  if command -v "$1" 2>&1 >/dev/null; then
    _PATH="$PATH"
    export _PATH
    return 0
  fi
  return 1
}

if ! __exists "$1"; then
  die "\"$1\" does not exist"
fi

cmd="$1"
shift
"$cmd" "$@"
