#!/bin/bash

ROOT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"

log() {
  printf "[generate-sk] %s\n" "$*"
}

main() {
  if ! command -v gopass 2>&1 > /dev/null; then
    i gopass
  fi

  if ! command -v gopass 2>&1 > /dev/null; then
    die "auto-installation failed; install gopass with pkgx, mise, apt, brew, etc. and make it available in your shell's PATH"
    return 1
  fi

  local GP_KEY_NAME="sk/litellm_master_$USER@$(hostname)"

  log "Creating $GP_KEY_NAME"

  gopass generate --print --symbols=false --force --clip "$GP_KEY_NAME" 51

  echo "sk-$(pbpaste)" | gopass insert --force "$GP_KEY_NAME" 2>&1

  gopass show "$GP_KEY_NAME"
}

cd "${ROOT_DIR}/../"
main "$@"
