#!/bin/bash

DIR="$(dirname "$(readlink -f "$0")")"

log() {
  printf "[i] %s\n" "$*"
}

__i() {
  if [ $# -eq 0 ]; then
    return 0
  fi

  local os=`uname -s`
  local mgr=
  local pkgs="$@"

  if exists pkgm; then
    err=0
    for pkg in "${pkgs[*]}"; do
      echo "Executing [pkgm install \"$pkg\"]. Continue?"
      read -r -p "Continue? [y/N] " ans && [[ $ans =~ ^[Yy]$ ]] || exit
      read -r -p "Use sudo? [y/N] " ans && [[ $ans =~ ^[Yy]$ ]] && sudo pkgm install "$pkg" || pkgm install "$pkg"
      err=$((err+$?))
    done

    [ $err -gt 0 ] && return $err
    log "Installed with pkgx!"
    return $?
  fi

  if exists brew; then
    mgr="brew install";
  fi

  if [ $os != "Darwin" ]; then
    if exists pacman; then
      mgr="sudo pacman -S";
    elif exists apt; then
      mgr="sudo apt install";
    elif exists yum; then
      mgr="sudo yum install";
    fi
  fi

  eval $(echo "$mgr $pkgs")

  if [ $? -ne 0 -a $os != "Darwin" ]; then
    if exists brew; then
      brew install "$pkgs"
    fi
  fi
}

__i "$@"
err=$?

if [ $err -gt 0 ]; then
  printf "[i] pkgx has failed: Error code [%s]\n" $err
fi
