#!/bin/bash

os=`uname -s`

get_for_mac() {
  ipaddress=`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'`
  gateway=`route -n get default | grep gateway | egrep -o "[0-9\.]+"`
  nameservers=`cat /etc/resolv.conf | egrep -o "[0-9\.]{4,}" | awk '{printf "%s%s", sep, $0; sep=", "} END{print ""}'`
}

main() {

  if [ $os = "Darwin" ]; then
    get_for_mac
  else
    get_for_mac
  fi

  echo "OS: $os"
  echo "IP Address: $ipaddress"
  echo "Gateway: $gateway"
  echo "Nameservers: $nameservers"
}

main "$@"
