#!/bin/bash

[ -z $SHELL_SETTINGS_DIR ] && source $HOME/github/shell-settings/scripts/.INIT

__isproxmox() {
  if type uname > /dev/null; then
    OS=$(uname | tr '[:upper:]' '[:lower:]')
    if [ "$OS" = "linux" ]; then
      if [[ "`uname -a`" =~ "Linux.*pve.*" ]]; then
        OS="proxmox"
        export OS
        return 0
      fi
    fi
  fi

  return 1
}

__isproxmox "$@"
