#!/bin/bash

_ASK=${MISE_SKIP_AUTO_INSTALL_PROMPT=-0}

if [ $_ASK -eq 0 ]; then
  if [ ! -f $HOME/.local/bin/mise ]; then
    echo "Auto installing mise then exiting..."
    echo "...unless cancelled within the next 10 seconds..."
    sleep 10
    curl https://mise.run | sh
  fi
fi

[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT

__mise() {
  if non_local_bin_path mise; then
    PATH=$NON_LOCAL_BIN_PATH
  else
    if [ -z "${MISE_PATH}" ]; then
      echo "Mise is not installed, see .zshrc file install locations"
      echo "Could add steps here to manually install mise..."
      printf "or run\n> curl https://mise.run | sh\n"
      exit 1
    fi

    export PATH="$(realpath `dirname ${MISE_PATH}`):${PATH}"
  fi

  mise "${@}"
}

__mise "${@}"
