#!/bin/bash

trap exit EXIT

DO_KILL=0

BLACK="\033[0;30m"
DARK_GRAY="\033[1;30m"
#RED="\033[0;31m"
LIGHT_RED="\033[1;31m"
#GREEN="\033[0;32m"
LIGHT_GREEN="\033[1;32m"
#BROWN_ORANGE="\033[0;33m"
#YELLOW="\033[0;33m"
# This is supposed to be yellow but it's not, and brown orange looks yellow so....
#YELLOW="\033[1;33m"
BLUE="\033[0;34m"
LIGHT_BLUE="\033[1;34m"
PURPLE="\033[0;35m"
LIGHT_PURPLE="\033[1;35m"
CYAN="\033[0;36m"
LIGHT_CYAN="\033[1;36m"
LIGHT_GRAY="\033[0;37m"
WHITE="\033[1;37m"
NC='\033[0m' # No Color

RED() {
  tput setaf 196
}

GREEN() {
  tput setaf 46
}

YELLOW() {
  tput setaf 220
}

WHITE() {
  tput setaf 15
}

log() {
  echo -e "$(GREEN)[$(WHITE)pa$(GREEN)] $(WHITE)$@${NC}"
}

exit() {
  return 1
  #echo -e "$(GREEN)[$(WHITE)pa$(GREEN)] $(RED)exit${NC}"
}

intro() {
  echo -e "$(GREEN)###################"
  echo -e "$(GREEN)### $(WHITE)ps aux (pa) $(GREEN)###"
  echo -e "$(GREEN)###################"
  echo -e "$NC"
}

_pa() {
  intro
  local results=
  local match=""
  local pids=

  for arg in "$@"; do
    results="$results$(ps aux | grep -i $arg | grep -v grep | grep -v "/shell-settings/scripts/pa "$arg"" | grep -v ' vim ' | grep -v ' tail ')"
  done

  if [ "$results" == "" ]; then
    log "No matches found"
    return 0
  fi

  while IFS= read -r f; do
    pid="$(echo $f | awk '{print $2}')"
    process="$(echo $f | awk '{$1=$2=$3=$4=$5=$6=$7=$8=$9=$10=""; print $0}' | sed -E 's#  +##g')"

    pids="$pids $pid"

    log "$(GREEN)[$(YELLOW)$pid$(GREEN)]$(WHITE) $process"
  done <<< "$results"

  if [ $DO_KILL -eq 1 ]; then
    echo "$pids" | xargs kill -9
  fi
}

main() {
  if [ "$1" == "-k" ]; then
    DO_KILL=1
    shift
    _pa "$@"
  else
    _pa "$@"
  fi
}

main "$@"
