#!/bin/bash

LEN="${1:-22}"

echo "[pw] create password with length: ${LEN}"

generatedpw="$(pkgx pwgen -c -n -y  -s -1 "${LEN}")"

echo "${generatedpw}" | tr -d '\n' | pbcopy

echo "[pw] ::: ${generatedpw} :::"
