#!/bin/bash

[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/_INIT

main() {
  if ! non_local_bin_path pkgo; then
    log "pkgo installation missing, running installer..."
    sudo pkgm install pkgo
  fi

  if non_local_bin_path pkgo; then
    export PATH=$NON_LOCAL_BIN_PATH
    pkgo "$@"
  else
    die "Unable to install or locate pkgo"
  fi
}

main "$@"
