#!/bin/bash
[ -z $SHELL_SETTINGS_INIT ] && source $HOME/github/shell-settings/scripts/.INIT

exists() {
  if ! command -v "$1" 2>&1 > /dev/null; then
    return 1
  fi
  return 0
}

doupgrade() {
  return 0
}

main() {
  if ! exists pkgx; then
    log "Installing pkgx: brew install pkgx || curl https://pkgx.sh | sh"
    brew install pkgx || curl https://pkgx.sh | sh
  fi

  if ! exists pkgx; then
    die "Something went wrong :("
  fi

  pkgx "$@"
}

DEBUG_PKGX="${DEBUG_PKGX:-0}"

if [ "$DEBUG_PKGX" -eq "1" ]; then
  if [ "$#" -ne "0" ]; then
    log "$@"
  fi
fi

main "$@"

