#!/bin/zsh

# Auto-screen invocation. see: http://taint.org/wk/RemoteLoginAutoScreen
# if we're coming from a remote SSH connection, in an interactive session
# then automatically put us into a screen(1) session.   Only try once
# -- if $STARTED_SCREEN is set, don't try it again, to avoid looping
# if screen fails for some reason.

export STARTED_SCREEN=${STARTED_SCREEN:-0}
export TERM=${TERM:-NOTERM}

print "\n[$USER@$HOST:$PWD]\n"

if [ $STARTED_SCREEN -eq 0 ]; then
  #################################################################
  # other things you want to run before screen starts can go here
  print "\n[$USER@$HOST:$PWD]\n"
  #################################################################

  if [ "$PS1" != "" -a $STARTED_SCREEN -eq 0 -a "${SSH_TTY:-x}" != x ]
  then
    STARTED_SCREEN=1
    echo "[~/.zshenv] setting up screen session"
    screen -RR -S zshenv && exit 0
    # You will only see this message if screen fails
    echo "Screen failed! continuing with normal bash startup"
  fi
else
  echo "[~/.zshenv] attached to a new screen session"
fi
# [end of auto-screen snippet]
