#!/bin/bash

[ ! "$_INIT_COMPLETE" ] && source $HOME/github/shell-settings/scripts/.INIT && export _INIT_COMPLETE=1

git_dir=$HOME/github/shell-settings
update_file=~/.config/shell-settings/last_updated

_update_shell_settings() {
  log "updating shell-settings"

  cd $git_dir && \
    git pull origin main --rebase --autostash && \
    date +%s > "$update_file"

  # if ping github.com -c1 -t1 > /dev/null; then
  # else
  #   echo "could not reach github.com"
  # fi
}

_since() {
  log "last updated:"
  log "  $diff_seconds seconds ago"
  log "  $diff_minutes minutes ago"
  log "  $diff_hours hours ago"
  log "  $diff_days days ago"
  echo ""
}

UPDATE_SHELL=1
UPDATE_VIM=2
UPDATE_MISE=4
UPDATE_TLDR=8

UPDATE_QUICK=3
UPDATE_LONG=12
UPDATE_ALL=15

run-updaters() {
  local updateflags=${1:-0}
  local checkflag=

  # zsh -ic "omz update"

  # Update shell
  checkflag=$UPDATE_SHELL
  if [ "$(( $checkflag & $updateflags))" = "$checkflag" ]; then
    log "Running update shell settings"
    _update_shell_settings
  fi

  # Update shell
  checkflag=$UPDATE_VIM
  if [ "$(( $checkflag & $updateflags))" = "$checkflag" ]; then
    log "Running update vim"
    vim -es -u $HOME/.vimrc -i NONE -c "PlugInstall" -c "qa"
  fi

  # Update shell
  checkflag=$UPDATE_MISE
  if [ "$(( $checkflag & $updateflags))" = "$checkflag" ]; then
    log "Updating mise..."
    if non_local_bin_path mise; then
      PATH="$NON_LOCAL_BIN_PATH:$PATH"
      log "Running mise self-update"
      mise self-update
    else
      log "! mise is not installed !"
    fi
  fi

  # Update shell
  checkflag=$UPDATE_TLDR
  if [ "$(( $checkflag & $updateflags))" = "$checkflag" ]; then
    log "Updating tldr..."
    if non_local_bin_path tldr; then
      PATH=$NON_LOCAL_BIN_PATH
      tldr -u
    else
      log "! tldr is not installed !"
    fi
  fi
}

run() {
  set +u
  if [ "$1" = "--force" ]; then
    log "run-updaters $UPDATE_ALL (\"--force\")"
    run-updaters $UPDATE_ALL
    set -u
    return 0
  fi
  set -u

  if [ -f "$update_file" ]; then
    now=$(date +%s)
    diff_seconds=$((now - `cat $update_file`))
    diff_minutes=$(($diff_seconds / 60))
    diff_hours=$(($diff_minutes / 60))
    diff_days=$(($diff_hours / 24))

    set +u
    if [ "$1" = "--since" ]; then
      set -u
      _since
      return 0
    fi
    set -u

    if [ $diff_days -gt 2 ]; then
      if [ ! -d $git_dir ]; then
        log "cannot find \"$git_dir\""
        return 1
      fi

      run-updaters $UPDATE_LONG
    fi

    if [ $diff_days -gt 1 ]; then
      if [ ! -d $git_dir ]; then
        log "cannot find \"$git_dir\""
        return 1
      fi

      _since
      run-updaters $UPDATE_QUICK
    fi
  else
    mkdir -p $(dirname "$update_file")
    date +%s > "$update_file"
  fi
}

. "$git_dir/setup_symlinks.sh"

run "$@"
