# .github/workflows/secret-scan.yml
name: secret-scan

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read          # checkout
  issues: write           # comment on issues/PRs
  pull-requests: write    # comment on PRs
  id-token: write         # allow TruffleHog to verify some cloud keys

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps   :
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.89.1
        with:
          path: ./
          extra_args: --only-verified

  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
