# .github/workflows/secret-scan.yml
name: secret-scan

on:
  push:
    branches: [main]
  pull_request:
  # uncomment if you also want to scan PRs from forks
  # pull_request_target:
  #   types: [opened, synchronize, reopened]

permissions:
  contents: read          # checkout
  issues: write           # comment on issues/PRs
  pull-requests: write    # comment on PRs
  id-token: write         # allow TruffleHog to verify some cloud keys

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history for git scan)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.89.1
        continue-on-error: true            # let the next step decide pass/fail
        with:
          scanMode: git                    # scan git history
          path: ./                         # repository root
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified      # fail only on confirmed secrets
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if verified secrets detected
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
