# .github/workflows/secret-scan.yml
name: secret-scan

on:
  push:
    branches: [main]
  pull_request:
  # uncomment if you also want to scan PRs from forks
  # pull_request_target:
  #   types: [opened, synchronize, reopened]

permissions:
  contents: read          # checkout
  issues: write           # comment on issues/PRs
  pull-requests: write    # comment on PRs
  id-token: write         # allow TruffleHog to verify some cloud keys

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps   :
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.89.1
        with:
          scanMode: filesystem          # scan the checked‑out code
          exit-code: true               # fail the job if secrets are found
          extraArgs: --only-verified    # report only verified findings
